server:
  port: 8003
spring:
  application:
    name: service-vod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB   #单个上传限制
      max-request-size: 1024MB #总上传限制

aliyun:
  vod:
    file:
      keyid: LTAI5tELYZYX9FG7DAQwfPHN
      keysecret: M4qyS39oKk3OOO4YpQO9OgEzf5GQsJ

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
